title: Online Waystation: Link Repository 
author: Hikin337
email: hikin337@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Go anywhere on the internet. Travel to yet unexplored resevoirs of information.

# social links
twitter_username: @NeeHiki
github_username:  Hikin337

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
